[package]
name = "presquile"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
csv = "1.3.0"
derive-new = "0.5.9"
id3 = "1.8.0"
metadata = "0.1.8"
serde = { version = "1.0.189", features = ["derive"] }

[workspace]
