name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntuhandbook1/ffmpeg7 \
        && sudo apt update \
        && sudo apt install -y ffmpeg build-essential clang libavutil-dev libavcodec-dev libavformat-dev
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Check Style
      run: cargo fmt --check
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test 
